#! /usr/bin/env python3

####################################################################################################
#
# wikijs-cli - A CLI for Wiki.js
# Copyright (C) 2025 Fabrice SALVAIRE
# SPDX-License-Identifier: GPL-3.0-or-later
#
####################################################################################################

####################################################################################################

from dataclasses import dataclass

from yaml import load
from yaml import Loader

from WikiJsTools.WikiJsApi import WikiJsApi
from WikiJsTools.Cli import Cli

####################################################################################################

@dataclass
class Config:
    API_URL: str
    API_KEY: str

####################################################################################################

with open('config.yaml') as fh:
    _ = load(fh, Loader=Loader)
    config = Config(**_)

api = WikiJsApi(api_url=config.API_URL, api_key=config.API_KEY)
cli = Cli(api)
cli.cli(query='')
